awwards_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from register import views as register_views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('register/',register_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='registration/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='registration/logout.html'),name='logout'),
    
    #PASSWORD RESET VEWS
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password/password_reset.html'),name='password_reset'),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),name='password_reset_complete'),
    #API AUTHENTICATION TOKEN
    path('api-auth-token/',obtain_auth_token)
]

project/urls.py
from django.urls import path,include
from .  import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from .views import ProjectList


# router=routers.DefaultRouter()
# router.register('project',views.ProjectList)

app_name='project'
urlpatterns = [
    path('', views.index,name='project_index'),
    path('user/profile/', views.profile,name='profile'),
    path('project/<int:project_id>/', views.project,name='project'),
    path('new/project/', views.new_project,name='new_project'),
    path('user/<int:user_id>', views.posted_by,name='posted_by'),
    #API PATTERN
    path('api/', views.api,name='api'),
    path('api/project/', views.ProjectList.as_view()),
    path('api/users/', views.UserList.as_view()),
    path('api/project/<int:pk>/',views.ProjectDescription.as_view()),
    path('api/user/<int:pk>/',views.UserDescription.as_view()),
    path('project/<int:project_id>/vote/',views.vote,name='vote'),
    path('update/user/',views.update_settings,name='update_settings'),
    
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator
from PIL import Image

# Create your models here.
class Project(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='project/')
    title=models.CharField(max_length=60)
    description=models.TextField()
    link=models.CharField(max_length=100)
    location=models.CharField(max_length=30)
    posted=models.DateTimeField(auto_now_add=True) 

    def save(self, *args, **kwargs):
        super().save()
        img=Image.open(self.image.path)
        
        if img.height>720 and img.width>720:
            size=(720,720)
            img.thumbnail(size)
            img.save(self.image.path)
        
    def __str__(self):
        return self.title
    
    def save_project(self):
        self.save()
    
    @classmethod    
    def get_project(cls, id):
        project=Project.objects.get(pk=id)
        return project
    
    @classmethod   
    def delete_project(cls,delete_id):
        Project.objects.filter(pk=delete_id).delete()
        
        
class Votes(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    project=models.ForeignKey(Project, on_delete=models.CASCADE)
    usability=models.IntegerField(default=0, validators=[MaxValueValidator(10,message='Range acceptable is 0-10'), MinValueValidator(0)])
    design=models.IntegerField(default=0, validators=[MaxValueValidator(10,message='Range acceptable is 0-10'), MinValueValidator(0)])
    content=models.IntegerField(default=0, validators=[MaxValueValidator(10,message='Range acceptable is 0-10'), MinValueValidator(0)])
    
    def __str__(self):
        return self.user.username
    
    
class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='profile/', default='default.png')
    bio=models.TextField(blank=True)
    contact=models.CharField(max_length=30, blank=True)
    location=models.CharField(max_length=50,  blank=True)
    company=models.CharField(max_length=50, blank=True)
    
    def __str__(self):
        return self.user.username
    
    def save(self,*args,**kwargs):
        super().save()
        
        img=Image.open(self.image.path)
        
        if img.height>400 and img.width>400:
            size=(400,400)
            img.thumbnail(size)
            img.save(self.image.path)
            

project/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Profile,Project,Votes

class UpdateUser(forms.ModelForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=['username', 'email']
        
class UpdateProfile(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['contact','location','bio','image']
        
        
        
class PostProject(forms.ModelForm):
    class Meta:
        model=Project
        fields=['image','title','description','link','location']
        
class Votes(forms.ModelForm):
    class Meta:
        model=Votes
        fields=['usability','design','content']

project/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required
from .models import Profile,Project
from .forms import PostProject,UpdateUser,UpdateProfile,Votes
from django.contrib.auth.models import User
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import ProjectSerailizer,UserSerializer
from rest_framework import status
from .permission import IsAdminOrReadOnly
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
import numpy as np

# Create your views here.
#api view
class ProjectList(APIView):
    def get(self,response,format=None):
        projects=Project.objects.all()
        serializer=ProjectSerailizer(projects,many=True)
        return Response(serializer.data)
    
    @login_required
    def post(self,request,format=None):
        permission_classes=(IsAdminOrReadOnly,)
        serializer=ProjectSerailizer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=status.HTTP_201_CREATED)
        
        return Response(serializer.errors,status=status.HTTP_400_BAD_REQUEST)
    
        permission_classes=(IsAdminOrReadOnly,)

class UserList(APIView):
    def get(self,response,format=None):
        users=User.objects.all()
        serializer=UserSerializer(users,many=True)
        return Response(serializer.data)
 
 #GETS A PROJECT BY AN ID 
class ProjectDescription(APIView):
    permission_classes=(IsAdminOrReadOnly,)  
    def get_project(self,pk):
        return get_object_or_404(Project,pk=pk)
    #gets project by id
    def get(self, request, pk ,format=None):
        project= self.get_project(pk)
        serializer=ProjectSerailizer(project)
        return Response(serializer.data)
    #updates a specific project
    def put(self, request,pk, format=None):
        project=self.get_project(pk)
        serializer=ProjectSerailizer(project,request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    #DELETES A PROJECT    
    def delete(self,request,pk,format=None):
        project=self.get_project(pk)
        project.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
        
#GETS USER BY ID        
class UserDescription(APIView):
    permission_classes=(IsAdminOrReadOnly,)  
    def get_user(self,pk):
        return get_object_or_404(User,pk=pk)
    #gets user by id
    def get(self, request, pk ,format=None):
        user= self.get_user(pk)
        serializer=UserSerializer(user)
        return Response(serializer.data)
    #updates a specific user
    def put(self, request,pk, format=None):
        user=self.get_user(pk)
        serializer=UserSerializer(user,request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    #DELETES A user   
    def delete(self,request,pk,format=None):
        user=self.get_user(pk)
        user.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
        
        
    


#Index view
def index(request):
    projects=Project.objects.order_by('-posted')
    return render(request,'project/index.html',{'projects':projects})

#user profile
@login_required
def profile(request):
    return render(request,'project/profile.html')


#specific project
@login_required
def project(request,project_id):
    project=get_object_or_404(Project,pk=project_id)
    votes=Votes()
    votes_list=project.votes_set.all()
    for vote in votes_list:
        vote_mean=[]
        usability=vote.usability
        vote_mean.append(usability)
        content=vote.content
        vote_mean.append(content)
        design=vote.design
        vote_mean.append(design)
        mean=np.mean(vote_mean)
        mean=round(mean,2)
        if mean:
            return render(request, 'project/project.html',{'project':project,'votes':votes,'votes_list':votes_list,'mean':mean})

        
    return render(request, 'project/project.html',{'project':project,'votes':votes,'votes_list':votes_list})

@login_required
def new_project(request):
    current_user=request.user
    if request.method=='POST':
        form=PostProject(request.POST,request.FILES)
        if form.is_valid():
            project=form.save(commit=False)
            project.user=current_user
            project.save()
        return redirect('project:project_index')
    
    else:
        form=PostProject()
        
    return render(request,'project/new_project.html',{'form':form})

@login_required
def posted_by(request, user_id):
    user=get_object_or_404(User,pk=user_id)
    return render(request,'project/posted_by.html', {'user':user})

@login_required
def vote(request, project_id):
    project=get_object_or_404(Project, pk=project_id)
    votes=Votes()
    votes=Votes(request.POST)
    if votes.is_valid():
        vote=votes.save(commit=False)
        vote.user=request.user
        vote.project=project
        vote.save() 
        messages.success(request,'Votes Successfully submitted')
        return HttpResponseRedirect(reverse('project:project',  args=(project.id,)))
    
    else:
        messages.warning(request,'ERROR! Voting Range is from 0-10')
        votes=Votes()     
    return render(request, 'project/project.html',{'project':project,'votes':votes})
        
    
    
def update_settings(request):
    update_user=UpdateUser(request.POST,instance=request.user)
    update_profile=UpdateProfile(request.POST,request.FILES,instance=request.user.profile)
    if update_user.is_valid() and update_profile.is_valid():
        update_user.save()
        update_profile.save()
        
        messages.success(request, 'Profile Updated Successfully')
        return redirect('project:profile')
    
    else:
        update_user=UpdateUser(instance=request.user)
        update_profile=UpdateProfile(instance=request.user.profile)
    return render(request, 'project/update_profile.html',{'update_user':update_user,'update_profile':update_profile})

#API PAGE
def api(request):
    return render(request,'project/api.html')

templates/project/api.html
{%extends "project/base.html"%}
{% load bootstrap4%}
{% block content %}
<div class="container">
  <div class="row">
      <div class="co-lg-2 col-md-2"></div>
      <div class="co-lg-8 col-md-8 mb-3">
          <legend class="text-center">How to use AwwardMe Api</legend>
          <div>
              <div>For better user experience and for developers who would like to use our AwwardMe data, we
                  developed and <span style="font-weight: bolder;">API</span> who help you out. To use our api we recommend
                  to use it on <a href="https://www.postman.com/downloads/">Postman</a> which s much easier to send the HTTP request 
                  i.e GET,POST,PUT,DELETE...
              </div><br>
              <div>
                Before you start using our api endpoints you need an <span style="font-weight: bolder;">Token Autheniticaton</span> only for registered users. On Postman 
                choose the POST http request method on the url place this url <span class="text-white bg-dark">www.awwardme.heroku.com/api-auth-token/</span> on the body
                on the postman pass you USERNAME and PASSWORD as the key and value. On the request results at the bottom on postman
                if successful you will get your token.               
              </div><br>
              <div>
                After token received you can now access <span style="font-weight: bolder;">user</span> and <span style="font-weight: bolder;">project</span> data using the following 
                links <span class="text-white bg-dark">www.awwardme.heroku.com/api/users/</span> and <span class="text-white bg-dark">www.awwardme.heroku.com/api/project/</span> respectively.
              </div><br>
              <div style="font-style: italic;">
                  Thank You. <br>
                  Regards Denis Mbugua (developer)
              </div>
          </div>
      </div>
      <div class="co-lg-2 col-md-2"></div>
  </div>
</div>

{% endblock %}

templates/project/base.html
{% load bootstrap4%}
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title%}
    <title>AwwardMe | {{title}}</title>
    {% else %}
    <title>AwwardMe</title>
    {% endif%}
    {% block styles %}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{%static 'css/register.css'%}"  >
        <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg header">
        <a class="navbar-brand " id='name' href="{% url 'project:project_index'%}" >AwwardMe</a>
        <a href="{% url 'project:profile' %}">{{user.username}}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon bg-dark" ></span>
        </button>
        <div class="collapse navbar-collapse float-right" id="navbarNavDropdown">
          <ul class="navbar-nav ">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'project:new_project'%}">Submit Project</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="color: black; background-color: #60b4df;">
                <a class="dropdown-item" href="{% url 'project:api'%}">API</a>
                <a class="dropdown-item" href="{% url 'password_reset'%}">Change Password</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    <div class="text-center">
        {% if messages %}
            {% for message in messages%}
                <div class="alert alert-{{message.tags}}">{{message}}</div>
            {% endfor%}
        {% endif %}
    </div>
    {% block content%}
    {% endblock %}
    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% bootstrap_javascript%}
    {% endblock %}
</body>
</html>

templates/project/index.html
{% extends 'project/base.html'%}
{% load bootstrap4 %}
{% load static %}
{% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{%static 'css/register.css'%}"  >
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        {%for project in projects%}
        <div class="col-lg-6 col-md-6 mt-2">
            <div class="card m-3" style="width: auto; margin-left: 10px;">
                <div class="conatiner">
                    <a href="{% url 'project:project' project.pk%}"><img src="{{project.image.url}}" class="card-img-top img-responsive image" id="image" alt="IMAGE" title="" style="height:70vh; width: 100%;" ></a>
                    <div class="title">
                        <!-- <p class="text">{{project.title}}</p> -->
                    </div>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{project.title}}</h5>
                    <p>By <a href="{% url 'project:posted_by' project.user.id%}">{{project.user.username}}</a><span class="float-right">From {{project.location}}</span></p>
                    <div class="text-center"><a class="btn button text-center btn-block"  href="{% url 'project:project' project.id%}">View site details</a></div>
                </div>
                
            </div>               
        </div>
        {%endfor%}
    </div>
</div>
{% endblock %}

templates/project/new_project.html
{% extends 'project/base.html'%}
{% load bootstrap4 %} 
{% load static %}
{% block content%}
<div class="container mt-3 mb-5">
    <div class="row">
        <div class="col-lg-2 col-md-2 col-xs-0"></div>
        <div class="col-lg-8 col-md-8">
            <legend class="text-center border ">Create Your Project For Display</legend>
            <form  action="{%url 'project:new_project'%}" method="post" enctype="multipart/form-data">
                {%csrf_token%}

                {% bootstrap_form form%}
                <input type="submit" class="btn btn-outline-success btn-block" value="Submit Project">
            </form>
        </div>
        <div class="col-lg-2 col-md-2 col-xs-0"></div>
    </div>
</div>
{% endblock%}

templates/project/posted_by.html
{% extends 'project/base.html'%}
{% load bootstrap4 %} 
{% load static %}
{% block styles %}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{%static 'css/register.css'%}"  >
        <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
{% endblock %}

{% block content%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 col-lg-2"></div>
        <div class="col-md-8 col-lg-8 col-sm-10">
            <div class="card  mt-3">
                <!-- new conatiner -->
                <div class="container-fluid" >
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-xs-12 ml-2 mt-2 ">
                            <img src="{{user.profile.image.url}}" class="img-circle rounded-circle image-fluid" alt="..." style="width: 220px; height: 220px;">
                        </div>
                    
                        <div class="col-lg-6 col-md-6 col-xs-12 mb-2" style="font-size: 0.8rem;">
                            <h2 class="card-title">{{user.username}}</h2>
                            <p class="card-text">Email Adress: {{user.email}}</p>
                            {% if user.profile.company%}
                            <p class="card-text">Location: {{user.profile.company}}</p>
                            {%endif%} 
                            {% if user.profile.location%}
                            <p class="card-text">Location: {{user.profile.location}}</p>
                            {%endif%} 
                            {% if user.profile.contact%}
                            <p class="card-text">Contact Me: {{user.profile.contact}}</p>
                            {%endif%} 
                            {% if user.profile.bio%}
                            <p class="card-text">About Me: {{user.profile.bio}}</p>
                            {%endif%} 
                            {% if request.user.id is user.id%}
                            <a href="#" class="btn btn-success btn-sm"><small>Update Settings</small></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 col-lg-2"></div>
    </div>

    <div class="row mt-3">
        <div class="col-lg-12 col-md-12" >
            <div class="row">
                {%for image in user.project_set.all%}
                <div class="col-lg-4 col-md-4 mb-2" style="padding-right: 10px;">
                    <div class="card" style="margin-left: 0px;">
                        <a href="#"><img src="{{image.image.url}}" class="card-img-top img-responsive index_image" id="image" alt="IMAGE" title="" style="height:50vh; width: 100%;" ></a>
                        <div class="card-body">
                            <div class="card-body">
                                <h5 class="card-title">{{image.title}}</h5>
                                <p>By <a href="{% url 'project:posted_by' image.user.id%}">{{image.user.username}}</a><span class="float-right">From {{image.location}}</span></p>
                                <div class="text-center"><a class="btn button text-center btn-block"  href="{{image.link}}">Visit Site</a></div>
                            </div>
                        </div>  
                    </div>               
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{% endblock%}

templates/project/profile.html
{% extends 'project/base.html'%}
{% load bootstrap4 %} 
{% load static %}
{% block title%}
{{user.username}}
{% endblock%}

{% block styles %}
        {% bootstrap_css %}
        <link rel="stylesheet" href="{%static 'css/register.css'%}"  >
        <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
{% endblock %}

{% block content%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 col-lg-2"></div>
        <div class="col-md-8 col-lg-8 col-sm-10">
            <div class="card  mt-3">
                <!-- new conatiner -->
                <div class="container-fluid" >
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-xs-12 ml-2 mt-2 ">
                            <img src="{{user.profile.image.url}}" class="img-circle rounded-circle image-fluid" alt="..." style="width: 220px; height: 220px;">
                        </div>
                    
                        <div class="col-lg-6 col-md-6 col-xs-12 mb-2" style="font-size: 0.8rem;">
                            <h2 class="card-title">{{user.username}}</h2>
                            <p class="card-text">Email Adress: {{user.email}}</p>
                            {% if user.profile.company%}
                            <p class="card-text">Location: {{user.profile.company}}</p>
                            {%endif%} 
                            {% if user.profile.location%}
                            <p class="card-text">Location: {{user.profile.location}}</p>
                            {%endif%} 
                            {% if user.profile.contact%}
                            <p class="card-text">Contact Me: {{user.profile.contact}}</p>
                            {%endif%} 
                            {% if user.profile.bio%}
                            <p class="card-text">About Me: {{user.profile.bio}}</p>
                            {%endif%} 
                
                            <a href="{% url  'project:update_settings' %}" class="btn btn-success btn-sm"><small>Update Settings</small></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2 col-lg-2"></div>
    </div>

    <div class="row mt-3">
        <div class="col-lg-12 col-md-12" >
            <div class="row">
                {%for image in user.project_set.all%}
                <div class="col-lg-4 col-md-4 mb-2" style="padding-right: 10px;">
                    <div class="card" style="margin-left: 0px;">
                        <a href="#"><img src="{{image.image.url}}" class="card-img-top img-responsive index_image" id="image" alt="IMAGE" title="" style="height:50vh; width: 100%;" ></a>
                        <div class="card-body">
                            <div class="card-body">
                                <h5 class="card-title">{{image.title}}</h5>
                                <p>By <a href="{% url 'project:posted_by' image.user.id%}">{{image.user.username}}</a><span class="float-right">From {{image.location}}</span></p>
                                <div class="text-center"><a class="btn button text-center btn-block"  href="{{image.link}}">View site details</a></div>
                            </div>
                        </div>  
                    </div>               
                </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{% endblock%}

templates/project/project.html
{% extends 'project/base.html'%}
{% load bootstrap4 %}
{% load static %}
{% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{%static 'css/register.css'%}"  >
    <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Poppins'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
{% endblock %}
{% block content %}
<div class="container">
    <div class="row mt-3 mb-3">
        <div class="col-mg-5 col-col-md-5 col-xs-12" >
            <img src="{{project.image.url}}" alt="" style="width: 100%; height: 80vh;" class="image-responsive">
        </div>
        <div class="col-mg-7 col-col-md-7 col-xs-12 ml-3 mt-3">
            <div class="form-inline"><h5>By <a href="{% url 'project:posted_by' project.user.id %}">{{project.user.username}}</a></h5>  <span class="small ml-3">{{project.posted |  date:"M d,Y,f A"}}</span></div>
            <h5 style="font-weight: bolder;">Description</h5>
            <p>{{project.description}}</p>
            <div>
                <p>
                    <a class="btn btn-primary btn-block btn-sm" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                      Vote Now
                    </a>
                  </p>
                  <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                        <form action="{% url 'project:vote' project.id %}" method="POST">
                        {% csrf_token%}
                            {% bootstrap_form votes%}
                            <input type="submit" value="Vote" class="btn btn-outline-success btn-sm">
                        </form>
                    </div>
                  </div>
                  
            </div>
        </div>
    </div>
    <div class="row mb-4">
    <div class="col-lg-1 col-md-1"></div>
    <div class="col-lg-9 col-md-9">
        {%if votes_list%}
            {% for vote in votes_list%}
                <div>
                    <table class="table">
                        <thead class="thead" style="background-color: #60b4df;">
                        <tr>
                            <th scope="col">User</th>
                            <th scope="col">Usability</th>
                            <th scope="col">Content</th>
                            <th scope="col">Design</th>
                            <th scope="col">Mean</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td scope="col">{{vote.user.username}}</td>
                            <td scope="col">{{vote.usability}}</td>
                            <td scope="col">{{vote.content}}</td>
                            <td scope="col">{{vote.design}}</td>
                            <td scope="col">{{mean}}</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            {% endfor %}
        {%else%}
        <div>
            <table class="table">
                <thead class="thead" style="background-color: #60b4df;">
                  <tr>
                    <th scope="col">User</th>
                    <th scope="col">Usability</th>
                    <th scope="col">Content</th>
                    <th scope="col">Design</th>
                    <th scope="col">Mean</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td scope="col">No Votes Yet</td>
                    <td scope="col">No Votes Yet</td>
                    <td scope="col">No Votes Yet</td>
                    <td scope="col">No Votes Yet</td>
                    <td scope="col">No Votes Yet</td>
                  </tr>
                </tbody>
              </table>
        </div>

        {% endif %}
    </div>
    <div class="col-lg-1 col-md-1"></div>
    </div>
</div>
{% endblock %}